SELECT ORG_NAME,
  SUM(CASE WHEN POSITION LIKE '%董事长%' THEN 1 ELSE 0 END) AS 董事长人数,  
  SUM(CASE WHEN POSITION LIKE '%总经理%'
           AND POSITION NOT LIKE '%副总经理%' THEN 1 ELSE 0 END) AS 总经理人数,  
  SUM(CASE WHEN POSITION LIKE '%法定代表人%' THEN 1 ELSE 0 END) AS 法定代表人人数,  
  SUM(CASE WHEN POSITION LIKE '%董事%'
           AND POSITION NOT LIKE '%董事长%'
           AND POSITION NOT LIKE '%董事会秘书%'
           AND POSITION NOT LIKE '%独立董事%'
           AND POSITION NOT LIKE '%非独立董事%' THEN 1 ELSE 0 END) AS 董事人数,  
  SUM(CASE WHEN POSITION LIKE '%副总经理%' THEN 1 ELSE 0 END) AS 副总经理人数,  
  SUM(CASE WHEN POSITION LIKE '%董事会秘书%' THEN 1 ELSE 0 END) AS 董事会秘书人数,  
  SUM(CASE WHEN POSITION LIKE '%独立董事%'
           AND POSITION NOT LIKE '%非独立董事%' THEN 1 ELSE 0 END) AS 独立董事人数
FROM company JOIN people ON company.ORG_CODE = people.ORG_CODE
GROUP BY ORG_NAME, REG_CAPITAL
ORDER BY REG_CAPITAL DESC
