SELECT DISTINCT ORG_NAME
FROM company
WHERE ORG_CODE IN ( 
  SELECT DISTINCT ORG_CODE
  FROM people
  WHERE RESUME LIKE '%武汉大学%')
      AND ORG_CODE NOT IN (
  SELECT ORG_CODE
  FROM people
  WHERE PERSON_NAME IN (
    SELECT DISTINCT PERSON_NAME
    FROM people
    WHERE RESUME NOT LIKE '%武汉大学%'));